name: voila-ppc
channels:
- conda-forge
dependencies:
- altair
- matplotlib-base
- numpy
- pandas
- ipywidgets
- jupyterlab>=3.1
- voila>=0.2.11
import altair as alt
import ipywidgets as widgets
from ipywidgets import interact
from ipywidgets import fixed
import matplotlib.pyplot as plt
